[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd400a9c5acbec0c980c38553c67b61d348ad0dd"
os = "windows"

    [[DSSP.download]]
    sha256 = "90e86074970f12bfed6df63b95c64e2938b28cf38441147663ab7adce9f8d5b1"
    url = "https://github.com/marcom/TestDeploy_Windows_DSSP_jll/releases/download/DSSP-v4.4.0+1/DSSP.v4.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[DSSP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd400a9c5acbec0c980c38553c67b61d348ad0dd"
os = "windows"

    [[DSSP.download]]
    sha256 = "90e86074970f12bfed6df63b95c64e2938b28cf38441147663ab7adce9f8d5b1"
    url = "https://github.com/marcom/TestDeploy_Windows_DSSP_jll/releases/download/DSSP-v4.4.0+1/DSSP.v4.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
